spring.application.name=SecLibTestApp
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

security.roleBasedAuthorizationEnabled=true
user.two-factor-auth-enabled=true
user.ip-locking-enabled=true
user.user-locking-enabled=true
user.password-policy-enabled=true
user.password-reset-enabled=true

user.ip-max-attempts= 3
user.ip-lock-time=  30000
user.user-max-attempts= 3
user.user-lock-time=  30000

user.password-policy.pattern=(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?]).{8,}
user.password-policy.entropy=60
cors.allowed-headers=Origin,Content-Type,Accept,Authorization
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-origins=http://localhost:3000
cors.allow-credentials=true

security.roles.ADMIN.permissions=ReadPost,WritePost
security.roles.USER.permissions=ReadPost,WritePost
security.roles.GUEST.permissions=ReadPost
session.filter.loginRequired=false
session.filter.roleForUnauthenticatedUsers=GUEST

csp.directives=default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; font-src 'self'; object-src 'none'; frame-src 'none';

sanitizer.allowed-elements=a,b,i,u,strong,em,p,br
sanitizer.allowed-attributes=href,src
sanitizer.allowed-protocols=http,https